
Epoch [1/30], Train Loss: 0.5814, Validation Loss: 1.2712
Epoch [2/30], Train Loss: 0.4540, Validation Loss: 0.4716
Epoch [3/30], Train Loss: 0.4251, Validation Loss: 0.4411
Epoch [4/30], Train Loss: 0.4023, Validation Loss: 0.4642
Epoch [5/30], Train Loss: 0.3965, Validation Loss: 0.3965
Epoch [6/30], Train Loss: 0.3774, Validation Loss: 0.4059
Epoch [7/30], Train Loss: 0.3652, Validation Loss: 0.4993
Epoch [8/30], Train Loss: 0.3641, Validation Loss: 0.5769
Epoch [9/30], Train Loss: 0.3406, Validation Loss: 0.3644
Epoch [10/30], Train Loss: 0.3294, Validation Loss: 0.3318
Epoch [11/30], Train Loss: 0.3284, Validation Loss: 0.4415
Epoch [12/30], Train Loss: 0.3133, Validation Loss: 0.3977
Epoch [13/30], Train Loss: 0.2969, Validation Loss: 0.3086
Epoch [14/30], Train Loss: 0.2885, Validation Loss: 0.2905
Epoch [15/30], Train Loss: 0.2761, Validation Loss: 0.2852
Epoch [16/30], Train Loss: 0.2755, Validation Loss: 0.3524
Epoch [17/30], Train Loss: 0.2585, Validation Loss: 0.2543
Epoch [18/30], Train Loss: 0.2520, Validation Loss: 0.2694
Epoch [19/30], Train Loss: 0.2536, Validation Loss: 0.4620
Epoch [20/30], Train Loss: 0.2419, Validation Loss: 0.3033
Epoch [21/30], Train Loss: 0.2441, Validation Loss: 0.2540
Epoch [22/30], Train Loss: 0.2359, Validation Loss: 0.2488
Epoch [23/30], Train Loss: 0.2330, Validation Loss: 0.4505
Epoch [24/30], Train Loss: 0.2266, Validation Loss: 0.2768
Epoch [25/30], Train Loss: 0.2185, Validation Loss: 0.2363
Epoch [26/30], Train Loss: 0.2200, Validation Loss: 0.2596
Epoch [27/30], Train Loss: 0.2125, Validation Loss: 0.2918
Epoch [28/30], Train Loss: 0.2088, Validation Loss: 0.2918
Epoch [29/30], Train Loss: 0.2065, Validation Loss: 0.2289
Epoch [30/30], Train Loss: 0.2034, Validation Loss: 0.2402
wandb: Waiting for artifact model_val_loss to be committed...
Exception ignored in: <function ModelCheckpoint.__del__ at 0x0000024C8B954790>
Traceback (most recent call last):
  File "C:\Users\alexa\Desktop\cvdl\model_checkpoint.py", line 27, in __del__
    self.write_artifact(save[0], save[1])
  File "C:\Users\alexa\Desktop\cvdl\model_checkpoint.py", line 34, in write_artifact
    artifact.wait()
  File "c:\users\alexa\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\artifacts\artifact.py", line 776, in wait
    result = self._save_handle.wait(timeout=timeout)
  File "c:\users\alexa\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\lib\mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "c:\users\alexa\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\lib\mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "c:\users\alexa\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\lib\mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "c:\users\alexa\appdata\local\programs\python\python39\lib\threading.py", line 574, in wait
    signaled = self._cond.wait(timeout)
  File "c:\users\alexa\appdata\local\programs\python\python39\lib\threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt:
wandb: Waiting for artifact model_mean_pixel_accuracy to be committed...
Exception ignored in: <function ModelCheckpoint.__del__ at 0x0000024C8B954790>
Traceback (most recent call last):
  File "C:\Users\alexa\Desktop\cvdl\model_checkpoint.py", line 27, in __del__
    self.write_artifact(save[0], save[1])
  File "C:\Users\alexa\Desktop\cvdl\model_checkpoint.py", line 34, in write_artifact
    artifact.wait()
  File "c:\users\alexa\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\artifacts\artifact.py", line 776, in wait
    result = self._save_handle.wait(timeout=timeout)
  File "c:\users\alexa\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\lib\mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "c:\users\alexa\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\lib\mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "c:\users\alexa\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\lib\mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "c:\users\alexa\appdata\local\programs\python\python39\lib\threading.py", line 574, in wait
    signaled = self._cond.wait(timeout)
  File "c:\users\alexa\appdata\local\programs\python\python39\lib\threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt:
wandb: Waiting for artifact model_mean_intersection_over_union to be committed...
Exception ignored in: <function ModelCheckpoint.__del__ at 0x0000024C8B954790>
Traceback (most recent call last):
  File "C:\Users\alexa\Desktop\cvdl\model_checkpoint.py", line 27, in __del__
    self.write_artifact(save[0], save[1])
  File "C:\Users\alexa\Desktop\cvdl\model_checkpoint.py", line 34, in write_artifact
    artifact.wait()
  File "c:\users\alexa\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\artifacts\artifact.py", line 776, in wait
    result = self._save_handle.wait(timeout=timeout)
  File "c:\users\alexa\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\lib\mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "c:\users\alexa\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\lib\mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "c:\users\alexa\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\lib\mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "c:\users\alexa\appdata\local\programs\python\python39\lib\threading.py", line 574, in wait
    signaled = self._cond.wait(timeout)
  File "c:\users\alexa\appdata\local\programs\python\python39\lib\threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt:
wandb: Waiting for artifact model_fw_intersection_over_union to be committed...
Exception ignored in: <function ModelCheckpoint.__del__ at 0x0000024C8B954790>
Traceback (most recent call last):
  File "C:\Users\alexa\Desktop\cvdl\model_checkpoint.py", line 27, in __del__
    self.write_artifact(save[0], save[1])
  File "C:\Users\alexa\Desktop\cvdl\model_checkpoint.py", line 34, in write_artifact
    artifact.wait()
  File "c:\users\alexa\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\artifacts\artifact.py", line 776, in wait
    result = self._save_handle.wait(timeout=timeout)
  File "c:\users\alexa\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\lib\mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "c:\users\alexa\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\lib\mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "c:\users\alexa\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\lib\mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "c:\users\alexa\appdata\local\programs\python\python39\lib\threading.py", line 574, in wait
    signaled = self._cond.wait(timeout)
  File "c:\users\alexa\appdata\local\programs\python\python39\lib\threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
